name: very_good_project
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  dio: ^4.0.4
  http: ^0.13.4
  equatable: ^2.0.3
  freezed_annotation:
  json_annotation:

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
  build_runner:
  freezed:
  json_serializable:
  logger:

flutter:
  uses-material-design: true
  generate: true
